include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    - "lib/core/intl/generated/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
