name: winguard
description: "A native Windows GUI for the winget command-line tool, built with Flutter."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  fluent_ui: ^4.12.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^15.2.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  window_manager: ^0.5.0

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  msix: ^3.16.9
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/core/intl/l10n
  output_dir: lib/core/intl/generated